/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'case-studies': CaseStudy;
    services: Service;
    posts: Post;
    packages: Package;
    authors: Author;
    categories: Category;
    testimonials: Testimonial;
    clients: Client;
    media: Media;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Long-form proof of work. Compose the body from blocks in whatever order the story needs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * The headline of the story, e.g. "Stitching Sustainability".
   */
  title: string;
  /**
   * Client or project name, e.g. "Crafted Fibers".
   */
  client: string;
  /**
   * One or two sentences used on cards, listings and link previews. Lead with the outcome.
   */
  summary: string;
  /**
   * e.g. "Sustainable Fashion".
   */
  industry?: string | null;
  year?: number | null;
  /**
   * Which services this project used. Drives the cross-links from each service page.
   */
  services?: (number | Service)[] | null;
  /**
   * Free-form labels used by the archive filter.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What was the problem the client came with?
   */
  challenge?: string | null;
  /**
   * What did Redendron do about it?
   */
  approach?: string | null;
  /**
   * What changed as a result? Be concrete.
   */
  outcome?: string | null;
  /**
   * Headline numbers. These carry more weight with high-value prospects than any amount of copy.
   */
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used on the archive grid, the hover preview and link previews.
   */
  coverImage: number | Media;
  /**
   * Full-bleed image at the top of the case study. Falls back to the cover.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional hex colour sampled from the project, used to tint this case study's page. Defaults to the brand oxblood.
   */
  accentColor?: string | null;
  /**
   * Add as many blocks as the story needs, in any order. Drag to reorder.
   */
  body?:
    | (
        | {
            /**
             * Optional section heading.
             */
            heading?: string | null;
            /**
             * Small label above the heading, e.g. "The challenge".
             */
            eyebrow?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            /**
             * Image drifts against the scroll. Ignored for reduced-motion visitors.
             */
            parallax?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            layout?: ('grid-2' | 'grid-3' | 'offset' | 'scroll') | null;
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            /**
             * Pin the text while the image scrolls past.
             */
            sticky?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'split';
          }
        | {
            heading?: string | null;
            stats: {
              /**
               * e.g. "312%", "4.2x", "60-page"
               */
              value: string;
              /**
               * What the number measures.
               */
              label: string;
              /**
               * Optional qualifier, e.g. "in the first 90 days".
               */
              detail?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            quote: string;
            /**
             * Name of the person quoted.
             */
            attribution?: string | null;
            /**
             * Their title and company.
             */
            role?: string | null;
            avatar?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullQuote';
          }
        | {
            before: number | Media;
            after: number | Media;
            beforeLabel?: string | null;
            afterLabel?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeAfter';
          }
        | {
            source?: ('upload' | 'embed') | null;
            file?: (number | null) | Media;
            url?: string | null;
            /**
             * Still frame shown before playback.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            text: string;
            tone?: ('accent' | 'muted' | 'inverted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  /**
   * Optional client quote pinned to the end of the study.
   */
  testimonial?: (number | null) | Testimonial;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug?: string | null;
  /**
   * Used for ordering. Can be backdated or set in the future.
   */
  publishedAt?: string | null;
  /**
   * Surface this on the homepage.
   */
  featured?: boolean | null;
  seo?: {
    /**
     * Falls back to the page title. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Shown in search results and link previews. Aim for 140-160 characters.
     */
    description?: string | null;
    /**
     * Social share image. Falls back to the cover image, then to a generated card.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * One line, shown under the title in the services accordion.
   */
  tagline?: string | null;
  /**
   * Used on listings, the homepage accordion and link previews.
   */
  summary: string;
  /**
   * Shown when a visitor hovers this service in the homepage accordion. Make it striking. The accordion degrades to a type-only treatment when this is empty, so a service can be drafted before its art exists.
   */
  previewImage?: (number | null) | Media;
  /**
   * What the client actually receives.
   */
  deliverables?:
    | {
        item: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The engagement, step by step. Rendered as a scroll-driven sequence.
   */
  process?:
    | {
        title: string;
        description: string;
        /**
         * e.g. "1-2 weeks"
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  body?:
    | (
        | {
            /**
             * Optional section heading.
             */
            heading?: string | null;
            /**
             * Small label above the heading, e.g. "The challenge".
             */
            eyebrow?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            /**
             * Image drifts against the scroll. Ignored for reduced-motion visitors.
             */
            parallax?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            layout?: ('grid-2' | 'grid-3' | 'offset' | 'scroll') | null;
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            /**
             * Pin the text while the image scrolls past.
             */
            sticky?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'split';
          }
        | {
            heading?: string | null;
            stats: {
              /**
               * e.g. "312%", "4.2x", "60-page"
               */
              value: string;
              /**
               * What the number measures.
               */
              label: string;
              /**
               * Optional qualifier, e.g. "in the first 90 days".
               */
              detail?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            quote: string;
            /**
             * Name of the person quoted.
             */
            attribution?: string | null;
            /**
             * Their title and company.
             */
            role?: string | null;
            avatar?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullQuote';
          }
        | {
            before: number | Media;
            after: number | Media;
            beforeLabel?: string | null;
            afterLabel?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeAfter';
          }
        | {
            source?: ('upload' | 'embed') | null;
            file?: (number | null) | Media;
            url?: string | null;
            /**
             * Still frame shown before playback.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            text: string;
            tone?: ('accent' | 'muted' | 'inverted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  /**
   * Also emitted as FAQ structured data for search engines.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedPackages?: (number | Package)[] | null;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show in the homepage services accordion.
   */
  featured?: boolean | null;
  seo?: {
    /**
     * Falls back to the page title. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Shown in search results and link previews. Aim for 140-160 characters.
     */
    description?: string | null;
    /**
     * Social share image. Falls back to the cover image, then to a generated card.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Sanity asset id, set during migration. Blank for anything uploaded since.
   */
  legacyId?: string | null;
  /**
   * Describe the image for screen readers and search engines. Leave blank only if the image is purely decorative.
   */
  alt?: string | null;
  /**
   * Optional visible caption, shown beneath the image where the layout supports it.
   */
  caption?: string | null;
  /**
   * Photographer or source attribution.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  title: string;
  /**
   * Who this is for, e.g. "For founders preparing to raise".
   */
  positioning?: string | null;
  summary: string;
  coverImage?: (number | null) | Media;
  /**
   * Shown as written, e.g. "From $12,000" or "On application". Free text so pricing can stay strategic.
   */
  priceLabel?: string | null;
  /**
   * e.g. "6-8 weeks".
   */
  timeline?: string | null;
  includes?:
    | {
        item: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  services?: (number | Service)[] | null;
  /**
   * The longer "what this actually is" paragraph.
   */
  whatsIncluded?: string | null;
  /**
   * The sequence, in order. Numbered automatically.
   */
  stages?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numbers we can stand behind. Keep it honest.
   */
  proof?:
    | {
        /**
         * e.g. "50+", ">20%".
         */
        value: string;
        label: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  body?:
    | (
        | {
            /**
             * Optional section heading.
             */
            heading?: string | null;
            /**
             * Small label above the heading, e.g. "The challenge".
             */
            eyebrow?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            /**
             * Image drifts against the scroll. Ignored for reduced-motion visitors.
             */
            parallax?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            layout?: ('grid-2' | 'grid-3' | 'offset' | 'scroll') | null;
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            /**
             * Pin the text while the image scrolls past.
             */
            sticky?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'split';
          }
        | {
            heading?: string | null;
            stats: {
              /**
               * e.g. "312%", "4.2x", "60-page"
               */
              value: string;
              /**
               * What the number measures.
               */
              label: string;
              /**
               * Optional qualifier, e.g. "in the first 90 days".
               */
              detail?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            quote: string;
            /**
             * Name of the person quoted.
             */
            attribution?: string | null;
            /**
             * Their title and company.
             */
            role?: string | null;
            avatar?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullQuote';
          }
        | {
            before: number | Media;
            after: number | Media;
            beforeLabel?: string | null;
            afterLabel?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeAfter';
          }
        | {
            source?: ('upload' | 'embed') | null;
            file?: (number | null) | Media;
            url?: string | null;
            /**
             * Still frame shown before playback.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            text: string;
            tone?: ('accent' | 'muted' | 'inverted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Visually emphasise this package in the pricing grid.
   */
  highlighted?: boolean | null;
  seo?: {
    /**
     * Falls back to the page title. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Shown in search results and link previews. Aim for 140-160 characters.
     */
    description?: string | null;
    /**
     * Social share image. Falls back to the cover image, then to a generated card.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  role?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Company logo, shown alongside the quote where the layout allows.
   */
  logo?: (number | null) | Media;
  /**
   * Optional link to the work this quote refers to.
   */
  caseStudy?: (number | null) | CaseStudy;
  /**
   * Eligible for the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown on cards and in link previews.
   */
  excerpt: string;
  coverImage: number | Media;
  body: (
    | {
        /**
         * Optional section heading.
         */
        heading?: string | null;
        /**
         * Small label above the heading, e.g. "The challenge".
         */
        eyebrow?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('contained' | 'wide' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        image: number | Media;
        caption?: string | null;
        width?: ('contained' | 'wide' | 'full') | null;
        /**
         * Image drifts against the scroll. Ignored for reduced-motion visitors.
         */
        parallax?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        layout?: ('grid-2' | 'grid-3' | 'offset' | 'scroll') | null;
        images: {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image: number | Media;
        imageSide?: ('left' | 'right') | null;
        /**
         * Pin the text while the image scrolls past.
         */
        sticky?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'split';
      }
    | {
        heading?: string | null;
        stats: {
          /**
           * e.g. "312%", "4.2x", "60-page"
           */
          value: string;
          /**
           * What the number measures.
           */
          label: string;
          /**
           * Optional qualifier, e.g. "in the first 90 days".
           */
          detail?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        quote: string;
        /**
         * Name of the person quoted.
         */
        attribution?: string | null;
        /**
         * Their title and company.
         */
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pullQuote';
      }
    | {
        before: number | Media;
        after: number | Media;
        beforeLabel?: string | null;
        afterLabel?: string | null;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'beforeAfter';
      }
    | {
        source?: ('upload' | 'embed') | null;
        file?: (number | null) | Media;
        url?: string | null;
        /**
         * Still frame shown before playback.
         */
        poster?: (number | null) | Media;
        caption?: string | null;
        width?: ('contained' | 'wide' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        text: string;
        tone?: ('accent' | 'muted' | 'inverted') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callout';
      }
  )[];
  author: number | Author;
  category: number | Category;
  /**
   * Minutes. Leave blank to calculate automatically from the body.
   */
  readingTime?: number | null;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug?: string | null;
  /**
   * Used for ordering. Can be backdated or set in the future.
   */
  publishedAt?: string | null;
  featured?: boolean | null;
  seo?: {
    /**
     * Falls back to the page title. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Shown in search results and link previews. Aim for 140-160 characters.
     */
    description?: string | null;
    /**
     * Social share image. Falls back to the cover image, then to a generated card.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Write each person once and reference them from posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * e.g. "Brand Strategist".
   */
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  links?: {
    linkedin?: string | null;
    instagram?: string | null;
    website?: string | null;
  };
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real taxonomy rather than a free-text field, so renaming a category updates every post at once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Shown on the category archive page.
   */
  description?: string | null;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos for the client marquee.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * SVG preferred. It will be rendered in a single flat colour.
   */
  logo: number | Media;
  /**
   * Optional link to the client site.
   */
  url?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every enquiry from the site. Never edited by the public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  source: 'quote' | 'contact' | 'newsletter';
  status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost';
  /**
   * Budget band selected in the quote form.
   */
  budget?: string | null;
  /**
   * When they want to start.
   */
  timeline?: string | null;
  company?: string | null;
  website?: string | null;
  businessDescription?: string | null;
  /**
   * What they want help with, and how they will measure success.
   */
  projectGoals?: string | null;
  /**
   * Contact-form message body.
   */
  message?: string | null;
  /**
   * Services they said they are interested in.
   */
  services?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * How they heard about Redendron.
   */
  referral?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes. Never shown publicly.
   */
  notes?: string | null;
  brevo?: {
    status?: ('pending' | 'synced' | 'failed' | 'skipped') | null;
    syncedAt?: string | null;
    error?: string | null;
  };
  meta?: {
    /**
     * Page the form was submitted from.
     */
    page?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  summary?: T;
  industry?: T;
  year?: T;
  services?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  challenge?: T;
  approach?: T;
  outcome?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  coverImage?: T;
  heroImage?: T;
  accentColor?: T;
  body?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              eyebrow?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              parallax?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              layout?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        split?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              image?: T;
              imageSide?: T;
              sticky?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              role?: T;
              avatar?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              source?: T;
              file?: T;
              url?: T;
              poster?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              text?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  testimonial?: T;
  slug?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  summary?: T;
  previewImage?: T;
  deliverables?:
    | T
    | {
        item?: T;
        detail?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        duration?: T;
        id?: T;
      };
  body?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              eyebrow?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              parallax?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              layout?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        split?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              image?: T;
              imageSide?: T;
              sticky?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              role?: T;
              avatar?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              source?: T;
              file?: T;
              url?: T;
              poster?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              text?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedPackages?: T;
  slug?: T;
  order?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  body?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              eyebrow?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              parallax?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              layout?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        split?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              image?: T;
              imageSide?: T;
              sticky?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              role?: T;
              avatar?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              source?: T;
              file?: T;
              url?: T;
              poster?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              text?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  author?: T;
  category?: T;
  readingTime?: T;
  slug?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  positioning?: T;
  summary?: T;
  coverImage?: T;
  priceLabel?: T;
  timeline?: T;
  includes?:
    | T
    | {
        item?: T;
        detail?: T;
        id?: T;
      };
  services?: T;
  whatsIncluded?: T;
  stages?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  proof?:
    | T
    | {
        value?: T;
        label?: T;
        detail?: T;
        id?: T;
      };
  body?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              eyebrow?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              parallax?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              layout?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        split?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              image?: T;
              imageSide?: T;
              sticky?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              role?: T;
              avatar?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              source?: T;
              file?: T;
              url?: T;
              poster?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              text?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  slug?: T;
  order?: T;
  highlighted?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  links?:
    | T
    | {
        linkedin?: T;
        instagram?: T;
        website?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  avatar?: T;
  logo?: T;
  caseStudy?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  legacyId?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  source?: T;
  status?: T;
  budget?: T;
  timeline?: T;
  company?: T;
  website?: T;
  businessDescription?: T;
  projectGoals?: T;
  message?: T;
  services?: T;
  referral?: T;
  notes?: T;
  brevo?:
    | T
    | {
        status?: T;
        syncedAt?: T;
        error?: T;
      };
  meta?:
    | T
    | {
        page?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Used as the default meta description suffix.
   */
  tagline?: string | null;
  /**
   * Used wherever the header sits on a pale background. Oxblood mark, ink wordmark.
   */
  logoLight?: (number | null) | Media;
  /**
   * The reversed lockup. Used in the footer and whenever the header is over a dark section.
   */
  logoDark?: (number | null) | Media;
  /**
   * Square. A PNG at 512x512 or an SVG both work.
   */
  favicon?: (number | null) | Media;
  /**
   * Fallback social share image for pages without their own.
   */
  defaultOgImage?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  socials?:
    | {
        platform: 'instagram' | 'linkedin' | 'behance' | 'dribbble' | 'x' | 'youtube' | 'facebook';
        url: string;
        id?: string | null;
      }[]
    | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logoLight?: T;
  logoDark?: T;
  favicon?: T;
  defaultOgImage?: T;
  email?: T;
  phone?: T;
  address?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}